name: CI
on: 
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: "0-59/5 0-23 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"
      - uses: actions/checkout@v2
      - name: Pip
        run: python3 -m pip install svgwrite
      - name: Main
        run: python main.py
      - name: Commit
        run: |
          git config --global user.name "https123456789/Repo-Stats"
          git config --global user.email "run[bot]@repo-stats.github.io"
          git add .
          git commit -m "Generated." || echo 
          git push
